In [1]:
!pip install faker

Collecting faker
  Downloading faker-40.35.0-py3-none-any.whl.metadata (16 kB)
Downloading faker-40.35.0-py3-none-any.whl (2.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 7.2 MB/s eta 0:00:00
Installing collected packages: faker
Successfully installed faker-40.35.0

In [2]:
import pandas as pd
import random
from faker import Faker
fake = Faker('en_IN')

In [3]:
import pandas as pd
import random
from faker import Faker
fake = Faker('en_IN')
branches = [
    "CSE",
    "CSM",
    "AIML",
    "DS",
    "ECE",
    "EEE",
    "IT"
]
students = []
for i in range(1, 201):
    students.append({
        "StudentID": i,
        "FullName": fake.name(),
        "Gender": random.choice(["Male", "Female"]),
        "Branch": random.choice(branches),
        "CGPA": round(random.uniform(6.5, 9.9), 2),
        "GraduationYear": 2027,
        "Email": fake.email(),
        "Phone": fake.msisdn()[:10]
    })
students_df = pd.DataFrame(students)
students_df.head()

,StudentID,FullName,Gender,Branch,CGPA,GraduationYear,Email,Phone
0,1,Ishani Thaman,Female,CSM,6.73,2027,azadhalder@example.net,6691467659
1,2,Aryan Rama,Male,ECE,6.99,2027,anyanigam@example.org,4482714517
2,3,Aadhya Mitra,Female,CSM,8.74,2027,sathvik06@example.net,7539359254
3,4,Girindra Sundaram,Male,AIML,7.66,2027,andrew09@example.net,3096218913
4,5,Nirja Lanka,Male,AIML,7.25,2027,thakerkritika@example.net,7701018681

In [4]:
students_df.to_csv("students.csv", index=False)

In [5]:
from google.colab import files
files.download("students.csv")

In [6]:
companies = [
    ["TCS","Software Engineer",7.0,"Hyderabad",7.0],
    ["Infosys","Systems Engineer",6.5,"Bangalore",6.5],
    ["Accenture","Associate Software Engineer",6.8,"Hyderabad",6.5],
    ["Capgemini","Analyst",6.2,"Pune",6.0],
    ["Cognizant","Programmer Analyst",6.5,"Chennai",6.5],
    ["Deloitte","Consultant",8.5,"Hyderabad",7.5],
    ["Amazon","SDE-1",28.0,"Bangalore",8.5],
    ["Microsoft","Software Engineer",32.0,"Hyderabad",8.8],
    ["Google","Software Engineer",40.0,"Hyderabad",9.0],
    ["Oracle","Application Developer",12.0,"Bangalore",7.5]
]

companies_df = pd.DataFrame(
    companies,
    columns=[
        "CompanyName",
        "Role",
        "Package",
        "Location",
        "EligibilityCGPA"
    ]
)

companies_df.insert(0,"CompanyID",range(1,len(companies_df)+1))

companies_df.head()

,CompanyID,CompanyName,Role,Package,Location,EligibilityCGPA
0,1,TCS,Software Engineer,7.0,Hyderabad,7.0
1,2,Infosys,Systems Engineer,6.5,Bangalore,6.5
2,3,Accenture,Associate Software Engineer,6.8,Hyderabad,6.5
3,4,Capgemini,Analyst,6.2,Pune,6.0
4,5,Cognizant,Programmer Analyst,6.5,Chennai,6.5

In [7]:
companies_df.to_csv("companies.csv",index=False)

In [8]:
files.download("companies.csv")

In [9]:
skills = [
"Python",
"SQL",
"Java",
"C",
"C++",
"Power BI",
"Tableau",
"Pandas",
"Numpy",
"Machine Learning",
"AWS",
"Git",
"Linux",
"Excel",
"DSA"
]

skills_df = pd.DataFrame({
    "SkillID":range(1,len(skills)+1),
    "SkillName":skills
})

skills_df.head()

   SkillID SkillName
0        1    Python
1        2       SQL
2        3      Java
3        4         C
4        5       C++

In [10]:
skills_df.to_csv("skills.csv",index=False)

In [11]:
files.download("skills.csv")

In [12]:
student_skills = []

skill_levels = ["Beginner", "Intermediate", "Advanced"]

student_skill_id = 1

for student in range(1,201):

    skills = random.sample(range(1,16), random.randint(3,6))

    for skill in skills:

        student_skills.append({
            "StudentSkillID": student_skill_id,
            "StudentID": student,
            "SkillID": skill,
            "SkillLevel": random.choice(skill_levels)
        })

        student_skill_id += 1

student_skills_df = pd.DataFrame(student_skills)

student_skills_df.head()

   StudentSkillID  StudentID  SkillID    SkillLevel
0               1          1        6      Beginner
1               2          1       15  Intermediate
2               3          1       13  Intermediate
3               4          1       10  Intermediate
4               5          1        5      Beginner

In [13]:
student_skills_df.to_csv("studentskills.csv",index=False)

In [14]:
files.download("studentskills.csv")

In [15]:
assessments = []

for i in range(1,501):

    student = random.randint(1,200)

    company = random.randint(1,10)

    assessments.append({

        "AssessmentID": i,

        "StudentID": student,

        "CompanyID": company,

        "CodingScore": random.randint(40,100),

        "SQLScore": random.randint(40,100),

        "AptitudeScore": random.randint(40,100),

        "AssessmentDate": fake.date_between("-1y","today"),

        "Status": random.choice(["Qualified","Rejected","Pending"])

    })

assessments_df = pd.DataFrame(assessments)

assessments_df.head()

,AssessmentID,StudentID,CompanyID,CodingScore,SQLScore,AptitudeScore,AssessmentDate,Status
0,1,120,9,94,41,94,2025-12-28,Pending
1,2,122,9,61,52,56,2025-09-18,Qualified
2,3,124,7,66,54,92,2025-09-29,Rejected
3,4,104,2,68,81,72,2025-12-21,Rejected
4,5,120,9,94,65,74,2025-07-27,Pending

In [16]:
assessments_df.to_csv("assessments.csv",index=False)

In [17]:
files.download("assessments.csv")

In [18]:
interviews = []

for i in range(1,301):

    interviews.append({

        "InterviewID": i,

        "StudentID": random.randint(1,200),

        "CompanyID": random.randint(1,10),

        "TechnicalRound": random.choice(["Pass","Fail"]),

        "HRRound": random.choice(["Pass","Fail","Pending"]),

        "InterviewDate": fake.date_between("-1y","today"),

        "Result": random.choice(["Selected","Rejected","Pending"])

    })

interviews_df = pd.DataFrame(interviews)

interviews_df.head()

,InterviewID,StudentID,CompanyID,TechnicalRound,HRRound,InterviewDate,Result
0,1,144,9,Pass,Pass,2026-03-31,Pending
1,2,32,3,Pass,Pass,2026-03-28,Selected
2,3,160,8,Fail,Pending,2026-02-04,Pending
3,4,184,9,Fail,Fail,2025-09-20,Pending
4,5,190,5,Pass,Pass,2025-12-06,Rejected

In [19]:
interviews_df.to_csv("interviews.csv",index=False)

In [20]:
files.download("interviews.csv")

In [21]:
offers = []

for i in range(1,151):

    offers.append({

        "OfferID": i,

        "StudentID": random.randint(1,200),

        "CompanyID": random.randint(1,10),

        "OfferedPackage": round(random.uniform(5,30),2),

        "OfferDate": fake.date_between("-1y","today"),

        "OfferStatus": random.choice(["Accepted","Rejected","Pending"])

    })

offers_df = pd.DataFrame(offers)

offers_df.head()

   OfferID  StudentID  CompanyID  OfferedPackage   OfferDate OfferStatus
0        1        156          3           26.63  2025-10-07    Rejected
1        2        135         10           16.93  2025-10-13     Pending
2        3        160          5           25.45  2026-01-03    Accepted
3        4         90          9           22.55  2025-07-25    Accepted
4        5         52          4            7.49  2025-11-09    Accepted

In [22]:
offers_df.to_csv("offers.csv",index=False)

In [23]:
files.download("offers.csv")